apt-get install -y \
  libboost-program-options-dev \
  libboost-program-options1.65.1 \
  libboost-system-dev \
  libeigen3-dev \
  libgraphicsmagick++1-dev \
  liblua5.2-dev \
  libsdl-image1.2-dev \
  libsdl1.2-dev \
  libyaml-cpp-dev \
  python3-pytest \
  python3-yaml \
  ros-eloquent-action-msgs \
  ros-eloquent-ament-cmake \
  ros-eloquent-ament-cmake-core \
  ros-eloquent-ament-cmake-gtest \
  ros-eloquent-ament-cmake-pytest \
  ros-eloquent-ament-cmake-python \
  ros-eloquent-ament-cmake-ros \
  ros-eloquent-ament-copyright \
  ros-eloquent-ament-flake8 \
  ros-eloquent-ament-lint-auto \
  ros-eloquent-ament-lint-common \
  ros-eloquent-ament-pep257 \
  ros-eloquent-angles \
  ros-eloquent-behaviortree-cpp-v3 \
  ros-eloquent-builtin-interfaces \
  ros-eloquent-cartographer \
  ros-eloquent-ecl-build \
  ros-eloquent-ecl-command-line \
  ros-eloquent-ecl-config \
  ros-eloquent-ecl-converters \
  ros-eloquent-ecl-devices \
  ros-eloquent-ecl-geometry \
  ros-eloquent-ecl-mobile-robot \
  ros-eloquent-ecl-sigslots \
  ros-eloquent-ecl-threads \
  ros-eloquent-ecl-time \
  ros-eloquent-geometry-msgs \
  ros-eloquent-laser-geometry \
  ros-eloquent-launch \
  ros-eloquent-launch-ros \
  ros-eloquent-launch-testing \
  ros-eloquent-launch-testing-ament-cmake \
  ros-eloquent-launch-testing-ros \
  ros-eloquent-lifecycle-msgs \
  ros-eloquent-map-msgs \
  ros-eloquent-message-filters \
  ros-eloquent-nav-msgs \
  ros-eloquent-osrf-pycommon \
  ros-eloquent-pcl-msgs \
  ros-eloquent-pluginlib \
  ros-eloquent-rclcpp \
  ros-eloquent-rclcpp-action \
  ros-eloquent-rclcpp-components \
  ros-eloquent-rclcpp-lifecycle \
  ros-eloquent-rclpy \
  ros-eloquent-robot-state-publisher \
  ros-eloquent-rosidl-default-generators \
  ros-eloquent-rosidl-default-runtime \
  ros-eloquent-sensor-msgs \
  ros-eloquent-std-msgs \
  ros-eloquent-std-srvs \
  ros-eloquent-test-msgs \
  ros-eloquent-tf2 \
  ros-eloquent-tf2-eigen \
  ros-eloquent-tf2-geometry-msgs \
  ros-eloquent-tf2-msgs \
  ros-eloquent-tf2-ros \
  ros-eloquent-tf2-sensor-msgs \
  ros-eloquent-urdf \
  ros-eloquent-urdfdom-headers \
  ros-eloquent-visualization-msgs \
  ros-eloquent-xacro \
  ros-eloquent-yaml-cpp-vendor 
