version: '3'
services:
  kojet:
    image: "192.168.1.11:5000/kojet-runtime"
    privileged: true
    volumes:
      - ~/install_aarch64:/ws
      - /dev:/dev
    working_dir: /ws
    entrypoint: /bin/bash -c "source setup.bash && ros2 launch robot_runtime robot_runtime.launch.py"
