version: '3'
services:
  kojet:
    image: robot_runtime
    privileged: true
    volumes:
      - /home/homey/data:/ros_ws/data
      - /home/homey/install_aarch64:/ros_ws/install
      - /dev:/dev
    entrypoint: /bin/bash -c "source install/setup.bash && ros2 launch robot_runtime robot_runtime.launch.py map_path:=/ros_ws/data/dillon.yaml nav:=true"
    tty: yes
    network_mode: host
