#!/bin/bash

docker run -it --rm \
    --name homey \
    --privileged \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -v /dev:/dev \
    -v $(pwd):/ws \
    -w /ws \
    homeydev:eloquent
