#!/bin/bash

docker run -it \
    --name homey --rm \
    --privileged \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -v /dev:/dev \
    -v $(pwd):/ws \
    -w /ws \
    --network=host \
    --entrypoint /bin/bash \
    emerson/native-ubuntu-eloquent
