#!/bin/bash

rocker \
  --x11 \
  --network host \
  --user \
  --oyr-run-arg "--name homey --rm -v $PWD:/ws -v /dev:/dev -w /ws --privileged --entrypoint /bin/bash" \
  -- emerson/x86_64-ubuntu-eloquent
